### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by ghost** [shabeersha/shoppingCart#1]
[https://sookart.herokuapp.com/](url) on images is not showing

**Comment by ghost** [comment]
i think the problem is gitignore file

**Comment by shabeersha** [comment]
The Heroku filesystem is ephemeral - that means that any changes to the filesystem whilst the dyno is running only last until that dyno is shut down or restarted. Each dyno boots with a clean copy of the filesystem from the most recent deploy. This is similar to how many container-based systems, such as Docker, operate.

In addition, under normal operations, dynos will restart every day in a process known as "Cycling".

**Comment by shabeersha** [comment]
The Heroku filesystem is ephemeral - that means that any changes to the filesystem whilst the dyno is running only last until that dyno is shut down or restarted. Each dyno boots with a clean copy of the filesystem from the most recent deploy. This is similar to how many container-based systems, such as Docker, operate.

In addition, under normal operations, dynos will restart every day in a process known as "Cycling".
